services:
  mysql:
    image: mysql:8.4
    container_name: webcraft-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_APP_USERNAME}
      MYSQL_PASSWORD: ${DB_APP_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: webcraft-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql-data: